name: direct_message
description: "Direct Message lets you send WhatsApp messages instantly by inputting a phone number, without the need to save contacts."
publish_to: 'none'
version: 2.0.0+5

environment:
  sdk: '>=3.13.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.5
  flutter_svg: ^2.3.0
  url_launcher: ^6.3.2
  google_fonts: ^8.2.1
  gap: ^3.0.1
  day_night_themed_switcher: ^2.0.2
  google_mobile_ads: ^9.1.0
  country_calling_code_kit: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: #e6f7ff
  adaptive_icon_foreground: "assets/images/launcher_icon.png"
  min_sdk_android: 21
  ios: true
  image_path_ios: "assets/images/launcher_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg