name: Deploy Static Site to Vercel

on:
  push:
    branches:
      - master
    paths:
      - 'site/**'
      - '.github/workflows/build_for_vercel.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Deploy on Vercel
        uses: amondnet/vercel-action@v42.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: site/
